import { and, eq, ne, sql } from "drizzle-orm";

import { db } from "../db";
import { collections } from "../db/schema";

// Nitro auto-imports everything under `server/utils/*`.

// Exact constraint names generated by drizzle-kit — confirmed against
// `server/db/migrations/0000_flawless_electro.sql`:
//   CONSTRAINT "collections_slug_unique" UNIQUE("slug")
//   CREATE UNIQUE INDEX "collections_user_id_name_unique" ON "collections" ...
// Postgres reports a unique-index violation's `.constraint` as the index
// name too (not just named table constraints), so both fire the same way.
const SLUG_UNIQUE_CONSTRAINT = "collections_slug_unique";
const NAME_UNIQUE_CONSTRAINT = "collections_user_id_name_unique";

interface NeonUniqueViolation {
  code: string;
  constraint?: string;
}

// `@neondatabase/serverless`'s `NeonDbError` (thrown as-is by
// drizzle-orm/neon-http — it does no wrapping, confirmed by reading
// `drizzle-orm/neon-http/session.js`) carries `pg`-style error fields
// directly on the error object: `.code` (e.g. "23505") and `.constraint`
// (the violated constraint/index name). Duck-typed here rather than an
// `instanceof` check so this doesn't need to import the driver's error class.
function isUniqueViolation(error: unknown): error is NeonUniqueViolation {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: unknown }).code === "23505"
  );
}

interface UniqueViolationInput {
  userId: string;
  name: string;
  slug: string;
  /** Current row's id on PATCH, so the re-query fallback doesn't flag a collection as colliding with itself. */
  excludeId?: string;
}

function slugTakenError(): never {
  throw createError({
    statusCode: 400,
    statusMessage: "Validation Error",
    data: { fieldErrors: { slug: ["This slug is already taken."] } }
  });
}

function nameTakenError(): never {
  throw createError({
    statusCode: 400,
    statusMessage: "Validation Error",
    data: { fieldErrors: { name: ["You already have a collection with this name."] } }
  });
}

/**
 * Maps a Postgres 23505 (unique_violation) raised by an insert/update against
 * `collections` to a field-level Validation Error. Primary path: read
 * `.constraint` off the caught error and match it against the two known
 * constraint names above. Fallback (constraint name absent or unrecognized —
 * e.g. a future migration renames it, or a driver upgrade changes the error
 * shape): re-query to determine whether the slug or the case-insensitive name
 * is what's actually taken by another row.
 *
 * Always throws: the mapped Validation Error, the re-derived one from the
 * fallback query, or (if neither the constraint name nor the fallback query
 * can explain the violation — e.g. a concurrent delete raced us) the
 * original error, unchanged, rather than inventing a field to blame. Also
 * rethrows unchanged if `error` isn't a 23505 at all.
 */
export async function throwCollectionUniqueViolation(
  error: unknown,
  input: UniqueViolationInput
): Promise<never> {
  if (!isUniqueViolation(error)) {
    throw error;
  }

  if (error.constraint === SLUG_UNIQUE_CONSTRAINT) {
    slugTakenError();
  }

  if (error.constraint === NAME_UNIQUE_CONSTRAINT) {
    nameTakenError();
  }

  const { userId, name, slug, excludeId } = input;

  const slugConflictWhere = excludeId
    ? and(eq(collections.slug, slug), ne(collections.id, excludeId))
    : eq(collections.slug, slug);
  const [slugConflict] = await db
    .select({ id: collections.id })
    .from(collections)
    .where(slugConflictWhere);

  if (slugConflict) {
    slugTakenError();
  }

  // Normalize in JS rather than binding the raw `name` into `trim(lower(...))`
  // SQL — same semantics as the DB's `collections_user_id_name_unique` index
  // expression, without relying on the driver's parameter-type inference
  // inside a function call.
  const normalizedName = name.trim().toLowerCase();
  const nameConflictWhere = and(
    eq(collections.userId, userId),
    sql`lower(trim(${collections.name})) = ${normalizedName}`,
    excludeId ? ne(collections.id, excludeId) : undefined
  );
  const [nameConflict] = await db
    .select({ id: collections.id })
    .from(collections)
    .where(nameConflictWhere);

  if (nameConflict) {
    nameTakenError();
  }

  throw error;
}
