import { and, eq } from "drizzle-orm";

import { db } from "../db";
import { collectionItems } from "../db/schema";

// Nitro auto-imports everything under `server/utils/*`. Mirrors
// `collection-errors.ts`'s structure exactly, scoped to the one constraint
// `collection_items` has.

// Exact constraint name generated by drizzle-kit — confirmed against the
// `uniqueIndex("collection_items_collection_id_url_id_unique")` definition in
// `server/db/schema.ts`.
const COLLECTION_ITEMS_UNIQUE_CONSTRAINT = "collection_items_collection_id_url_id_unique";

interface NeonUniqueViolation {
  code: string;
  constraint?: string;
}

// `@neondatabase/serverless`'s `NeonDbError` carries `pg`-style error fields
// directly on the error object: `.code` (e.g. "23505") and `.constraint`.
// Duck-typed rather than an `instanceof` check, same reasoning as
// `collection-errors.ts`.
function isUniqueViolation(error: unknown): error is NeonUniqueViolation {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: unknown }).code === "23505"
  );
}

interface UniqueViolationInput {
  collectionId: string;
  urlId: string;
}

function alreadyInCollectionError(): never {
  throw createError({
    statusCode: 400,
    statusMessage: "Validation Error",
    data: { fieldErrors: { url: ["This link is already in this collection."] } }
  });
}

/**
 * Maps a Postgres 23505 (unique_violation) raised by an insert against
 * `collection_items` to a field-level Validation Error. Primary path: read
 * `.constraint` off the caught error and match it against the known
 * constraint name above. Fallback (constraint name absent or unrecognized):
 * re-select the existing `(collectionId, urlId)` row — if found, the race
 * actually happened, so still throw the same field error; otherwise rethrow
 * the original error unchanged rather than inventing a field to blame. Also
 * rethrows unchanged if `error` isn't a 23505 at all.
 */
export async function throwLinkUniqueViolation(
  error: unknown,
  input: UniqueViolationInput
): Promise<never> {
  if (!isUniqueViolation(error)) {
    throw error;
  }

  if (error.constraint === COLLECTION_ITEMS_UNIQUE_CONSTRAINT) {
    alreadyInCollectionError();
  }

  const { collectionId, urlId } = input;
  const [existing] = await db
    .select({ id: collectionItems.id })
    .from(collectionItems)
    .where(and(eq(collectionItems.collectionId, collectionId), eq(collectionItems.urlId, urlId)));

  if (existing) {
    alreadyInCollectionError();
  }

  throw error;
}
